template_path: sec/iam/user.yaml
capabilities: CAPABILITY_IAM
parameters:
  Fullname: 'Test User 03'
  UserName: 'testuser03@cpc'
  Site: 'Davao'
  Team: 'E-Commerce'
  Groups:
    - !stack_output sec/iam/roles.yaml::opCpcDevGrp2
